/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package my-document-shelf-0.1.0.0 */
#ifndef VERSION_my_document_shelf
#define VERSION_my_document_shelf "0.1.0.0"
#endif /* VERSION_my_document_shelf */
#ifndef MIN_VERSION_my_document_shelf
#define MIN_VERSION_my_document_shelf(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_my_document_shelf */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package base-4.20.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.20.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  20 || \
  (major1) == 4 && (major2) == 20 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package bytestring-0.12.2.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.2.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 2)
#endif /* MIN_VERSION_bytestring */
/* package hakyll-4.16.7.1 */
#ifndef VERSION_hakyll
#define VERSION_hakyll "4.16.7.1"
#endif /* VERSION_hakyll */
#ifndef MIN_VERSION_hakyll
#define MIN_VERSION_hakyll(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 7)
#endif /* MIN_VERSION_hakyll */
/* package text-2.1.3 */
#ifndef VERSION_text
#define VERSION_text "2.1.3"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* tool alex-3.5.4.0 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.4.0"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-16.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "16.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  16 || \
  (major1) == 16 && (major2) <  0 || \
  (major1) == 16 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.10.3 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.10.3"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.10.3 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.10.3"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.31.1 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.31.1"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.1.7 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.1.7"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 7)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-2.3.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "2.3.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.10.3 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.10.3"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  10 || \
  (major1) == 9 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "my-document-shelf-0.1.0.0-HtCZTZb897DHZxVw3hWvR5-my-document-shelf"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
