name: Deploy Hakyll Site with Stack

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haskell (Stack)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4'
          stack-version: '2.15.1'

      - name: Build and Run Hakyll (Generate _site)
        run: |
          stack clean
          stack build
          stack exec my-document-shelf clean
          stack exec my-document-shelf build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site