name: Deploy Hakyll Site with Stack

on:
  push:
    branches:
      - main # mainブランチにプッシュされたら実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Haskell環境のセットアップ (Stackを使用)
      - name: Setup Haskell (Stack)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.4' # お使いのGHCバージョンに合わせてください
          stack-version: '2.15.1' # お使いのStackバージョンに合わせてください
          # build-tool: 'stack' # Stackをデフォルトのビルドツールとして設定（任意）

      # 2. Hakyllのビルドと実行
      - name: Build and Run Hakyll (Generate _site)
        run: |
          stack clean
          stack build
          stack exec my-document-shelf clean
          stack exec my-document-shelf build

      # 3. _siteフォルダをGitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site # Hakyllが出力するフォルダ